# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fusion/dev/ui files/MyTerrainManagerDock.ui'
#
# Created: Sun May  3 13:23:32 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TerrainManagerUi(object):
    def setupUi(self, TerrainManagerUi):
        TerrainManagerUi.setObjectName("TerrainManagerUi")
        TerrainManagerUi.resize(443, 626)
        self.gridLayout_2 = QtGui.QGridLayout(TerrainManagerUi)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtGui.QComboBox(TerrainManagerUi)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 0, 0, 1, 1)
        self.toolBox = QtGui.QToolBox(TerrainManagerUi)
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        #self.toolBox.setTabSpacing(1)
        self.toolBox.setObjectName("toolBox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 441, 515))
        self.page.setObjectName("page")
        self.gridLayout_3 = QtGui.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.nameLineEdit = QtGui.QLineEdit(self.groupBox)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.sizeComboBox = QtGui.QComboBox(self.groupBox)
        self.sizeComboBox.setObjectName("sizeComboBox")
        self.sizeComboBox.addItem(QtCore.QString())
        self.sizeComboBox.addItem(QtCore.QString())
        self.sizeComboBox.addItem(QtCore.QString())
        self.sizeComboBox.addItem(QtCore.QString())
        self.sizeComboBox.addItem(QtCore.QString())
        self.sizeComboBox.addItem(QtCore.QString())
        self.sizeComboBox.addItem(QtCore.QString())
        self.sizeComboBox.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.sizeComboBox, 2, 1, 1, 1)
        self.extendsSpinBoxX = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extendsSpinBoxX.sizePolicy().hasHeightForWidth())
        self.extendsSpinBoxX.setSizePolicy(sizePolicy)
        self.extendsSpinBoxX.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.extendsSpinBoxX.setMinimum(128)
        self.extendsSpinBoxX.setMaximum(10000)
        self.extendsSpinBoxX.setObjectName("extendsSpinBoxX")
        self.gridLayout.addWidget(self.extendsSpinBoxX, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.extendsSpinBoxX_2 = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extendsSpinBoxX_2.sizePolicy().hasHeightForWidth())
        self.extendsSpinBoxX_2.setSizePolicy(sizePolicy)
        self.extendsSpinBoxX_2.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.extendsSpinBoxX_2.setMinimum(128)
        self.extendsSpinBoxX_2.setMaximum(10000)
        self.extendsSpinBoxX_2.setObjectName("extendsSpinBoxX_2")
        self.gridLayout.addWidget(self.extendsSpinBoxX_2, 4, 1, 1, 1)
        self.extendsSpinBoxX_3 = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extendsSpinBoxX_3.sizePolicy().hasHeightForWidth())
        self.extendsSpinBoxX_3.setSizePolicy(sizePolicy)
        self.extendsSpinBoxX_3.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.extendsSpinBoxX_3.setMinimum(128)
        self.extendsSpinBoxX_3.setMaximum(10000)
        self.extendsSpinBoxX_3.setObjectName("extendsSpinBoxX_3")
        self.gridLayout.addWidget(self.extendsSpinBoxX_3, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        self.baseNameLineEdit = QtGui.QLineEdit(self.groupBox)
        self.baseNameLineEdit.setObjectName("baseNameLineEdit")
        self.gridLayout.addWidget(self.baseNameLineEdit, 7, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.baseNameLineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.baseNameLineEdit_2.setObjectName("baseNameLineEdit_2")
        self.gridLayout.addWidget(self.baseNameLineEdit_2, 8, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.sizeComboBox_2 = QtGui.QComboBox(self.groupBox)
        self.sizeComboBox_2.setObjectName("sizeComboBox_2")
        self.sizeComboBox_2.addItem(QtCore.QString())
        self.sizeComboBox_2.addItem(QtCore.QString())
        self.sizeComboBox_2.addItem(QtCore.QString())
        self.sizeComboBox_2.addItem(QtCore.QString())
        self.sizeComboBox_2.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.sizeComboBox_2, 9, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.sizeComboBox_3 = QtGui.QComboBox(self.groupBox)
        self.sizeComboBox_3.setObjectName("sizeComboBox_3")
        self.sizeComboBox_3.addItem(QtCore.QString())
        self.sizeComboBox_3.addItem(QtCore.QString())
        self.sizeComboBox_3.addItem(QtCore.QString())
        self.sizeComboBox_3.addItem(QtCore.QString())
        self.sizeComboBox_3.addItem(QtCore.QString())
        self.sizeComboBox_3.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.sizeComboBox_3, 10, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.page)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 3, 0, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 441, 515))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.Seite = QtGui.QWidget()
        self.Seite.setObjectName("Seite")
        self.toolBox.addItem(self.Seite, "")
        self.gridLayout_2.addWidget(self.toolBox, 1, 0, 1, 1)

        self.retranslateUi(TerrainManagerUi)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TerrainManagerUi)

    def retranslateUi(self, TerrainManagerUi):
        TerrainManagerUi.setWindowTitle(QtGui.QApplication.translate("TerrainManagerUi", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("TerrainManagerUi", "Terrain Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TerrainManagerUi", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TerrainManagerUi", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TerrainManagerUi", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox.setItemText(0, QtGui.QApplication.translate("TerrainManagerUi", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox.setItemText(1, QtGui.QApplication.translate("TerrainManagerUi", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox.setItemText(2, QtGui.QApplication.translate("TerrainManagerUi", "32", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox.setItemText(3, QtGui.QApplication.translate("TerrainManagerUi", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox.setItemText(4, QtGui.QApplication.translate("TerrainManagerUi", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox.setItemText(5, QtGui.QApplication.translate("TerrainManagerUi", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox.setItemText(6, QtGui.QApplication.translate("TerrainManagerUi", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox.setItemText(7, QtGui.QApplication.translate("TerrainManagerUi", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.extendsSpinBoxX.setPrefix(QtGui.QApplication.translate("TerrainManagerUi", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TerrainManagerUi", "Extends", None, QtGui.QApplication.UnicodeUTF8))
        self.extendsSpinBoxX_2.setPrefix(QtGui.QApplication.translate("TerrainManagerUi", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.extendsSpinBoxX_3.setPrefix(QtGui.QApplication.translate("TerrainManagerUi", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("TerrainManagerUi", "Splatting Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setToolTip(QtGui.QApplication.translate("TerrainManagerUi", "Base name for the map textures (will be appended by their number)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TerrainManagerUi", "Base Name", None, QtGui.QApplication.UnicodeUTF8))
        self.baseNameLineEdit.setToolTip(QtGui.QApplication.translate("TerrainManagerUi", "Base name for the map textures (will be appended by their number)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setToolTip(QtGui.QApplication.translate("TerrainManagerUi", "The resource group the textures will be placed in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TerrainManagerUi", "Res Group", None, QtGui.QApplication.UnicodeUTF8))
        self.baseNameLineEdit_2.setToolTip(QtGui.QApplication.translate("TerrainManagerUi", "The resource group the textures will be placed in", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setToolTip(QtGui.QApplication.translate("TerrainManagerUi", "Texture size in pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("TerrainManagerUi", "Tex Size", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_2.setToolTip(QtGui.QApplication.translate("TerrainManagerUi", "Texture size in pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_2.setItemText(0, QtGui.QApplication.translate("TerrainManagerUi", "64", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_2.setItemText(1, QtGui.QApplication.translate("TerrainManagerUi", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_2.setItemText(2, QtGui.QApplication.translate("TerrainManagerUi", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_2.setItemText(3, QtGui.QApplication.translate("TerrainManagerUi", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_2.setItemText(4, QtGui.QApplication.translate("TerrainManagerUi", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setToolTip(QtGui.QApplication.translate("TerrainManagerUi", "Number of splatting textures (Layers)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("TerrainManagerUi", "NumTextures", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_3.setToolTip(QtGui.QApplication.translate("TerrainManagerUi", "Number of splatting textures (Layers)", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_3.setItemText(0, QtGui.QApplication.translate("TerrainManagerUi", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_3.setItemText(1, QtGui.QApplication.translate("TerrainManagerUi", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_3.setItemText(2, QtGui.QApplication.translate("TerrainManagerUi", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_3.setItemText(3, QtGui.QApplication.translate("TerrainManagerUi", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_3.setItemText(4, QtGui.QApplication.translate("TerrainManagerUi", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.sizeComboBox_3.setItemText(5, QtGui.QApplication.translate("TerrainManagerUi", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("TerrainManagerUi", "Create Terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("TerrainManagerUi", "Create Terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("TerrainManagerUi", "ModifyTerrain", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Seite), QtGui.QApplication.translate("TerrainManagerUi", "PaintTerrain", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    TerrainManagerUi = QtGui.QWidget()
    ui = Ui_TerrainManagerUi()
    ui.setupUi(TerrainManagerUi)
    TerrainManagerUi.show()
    sys.exit(app.exec_())

