######################################################################
# Automatically generated by qmake (2.01a) Mo Dez 24 12:49:33 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
RESOURCES = rldialog.qrc
QT += xml

# Input
HEADERS += rldialog.h helper.h editor.h ifdialog.h
SOURCES += rldialog.cpp main.cpp helper.cpp editor.cpp ifdialog.cpp
