######################################################################
# Automatically generated by qmake (2.01a) Mi Sep 24 12:02:02 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
HEADERS += editor.h helper.h ifdialog.h rldialog.h
SOURCES += editor.cpp helper.cpp ifdialog.cpp main.cpp rldialog.cpp
RESOURCES += rldialog.qrc
